name: Daily Commit
on:
  schedule:
    - cron: '0 14 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Choose random line
        run: |
          line=$(shuf -n 1 content.txt)
          echo "$line" > content.txt
      - name: Commit changes
        run: git config user.email "zidan.5230411107@student.uty.ac.id"
        run: git config user.name "ZidanAlfianMubarok"
        run: git add content.txt
        run: git commit -m "Daily commit: $line"
        run: git push
test
